url: "https://roymauro.com"
baseurl: ""

title: "Rocío y Mauro"
description: "Somos una casualidad llena de intención."
keywords:
  - "wedding"
  - "invitation"
  - "card"
  - "casamiento"
  - "invitacion"
  - "tarjeta"
  - "rocio"
  - "mauro"
